### ISSUE TITLE
help

### ISSUE THREAD

**Issue by wermaxta** [adtac/autovpn#2]
Hi i need help My OS is Kali Linux 2016.2  i have install openvpn
when i type 
go build autovpn
I get this 
can't load package: package autovpn: cannot find package "autovpn" in any of:
	/usr/lib/go-1.7/src/autovpn (from $GOROOT)
	($GOPATH not set)

**Comment by franky303** [comment]
try:
go build autovpn.go

**Comment by wermaxta** [comment]
Thank you :)))))

**Comment by adtac** [comment]
Argh, sorry about that. Fixed it in https://github.com/adtac/autovpn/commit/b09a162ee31229f781d06ab946fbd5bb29a247f4

Thanks for bringing this up :)
