### ISSUE TITLE
Node.js version

### ISSUE THREAD

**Issue by rodrigogs** [adtac/autovpn#9]
Hey there!

I inspired myself into your project to create a node.js similar one.

Check it out: https://github.com/rodrigogs/easyvpn

**Comment by adtac** [comment]
Haha, that's nice :)

Anyway, this isn't really an issue :P close this?

**Comment by rodrigogs** [comment]
Man, issues are for general purpose :P
I'm closing anyway, just wanted to let you know.

**Comment by adtac** [comment]
Starred it :)

And I remember seeing the HN post btw; reached the frontpage
